### ISSUE TITLE
Struggling with old packages in virtualenv

### ISSUE THREAD

**Issue by christofs** [redewiedergabe/tagger#4]
Hi there, trying to get the scripts to run but no luck so far. 

I've installed all required packages in the correct versions as specified in the `requirements.txt` in a virtual environment, and downloaded both the BERT and the (default) FLAIR model for direct speech recognition to the right folder. I'm also using the "original" version of Python, that is 3.7, because I am otherwise getting errors related to flair not importing the BertEmbeddings correctly. 

However, when I launch the script, I get an error message related to the missing CUDA support of pytorch1.10 for my GPU, an Nvidia RTX 3060. Of course, I cannot upgrade pytorch to work with my CPU, because then I would not be compatible with the RW models anymore. 

Strangely, this happens despite the fact that I did not set the "gpu" parameter and the code should not attempt to use the GPU, and just use the CPU instead. 

So my question is, how and where in the code can I disable the (failing) attempt to use the GPU? Any hints would be very much appreciated. 

Below is the output from running rwtagger.py

```
(rwenv37) christof@aorus:~/Desktop/rw/tagger/rwtagger$ python rwtagger.py plain tagged -t direct -conf
2024-01-27 17:26:17,486 loading file /home/christof/Desktop/rw/tagger/rwtagger/models/direct/final-model.pt
/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "rwtagger.py", line 98, in <module>
    config_path=config_path
  File "/home/christof/Desktop/rw/tagger/rwtagger/pipeline.py", line 75, in predict
    special_model_path=model_paths_dict[available_rwtypes[0]])
  File "/home/christof/Desktop/rw/tagger/rwtagger/tagger.py", line 356, in predict
    model = SequenceTagger.load(model_path)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/flair/nn/model.py", line 135, in load
    model = cls._init_model_with_state_dict(state)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 286, in _init_model_with_state_dict
    reproject_embeddings=reproject_embeddings,
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/flair/models/sequence_tagger_model.py", line 229, in __init__
    self.to(flair.device)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/flair/models/language_model.py", line 476, in _apply
    child_module._apply(fn)
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 189, in _apply
    self.flatten_parameters()
  File "/home/christof/Desktop/rw/tagger/rwenv37/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(rwenv37) christof@aorus:~/Desktop/rw/tagger/rwtagger$ 
``` 

I've already tried the following, in various places / scripts (tagger.py, pipeline.py, rwtagger.py): 

``` 
os.environ['CUDA_VISIBLE_DEVICES'] = ''   ## Set to an empty string; Setting it to "1" also does not help. 
device = torch.device("cpu")
``` 

Unfortunately, that does not help.

**Comment by christofs** [comment]
Just to note, the following DID work on a laptop without GPU. (In any case, the issue described above is probably not related directly to rwtagger, but more general.)  

1. Start at: [https://github.com/redewiedergabe/tagger](https://github.com/redewiedergabe/tagger)
1. Download or clone the repository to a folder called `tagger` 
1. Download models (e.g. FLAIR and BERT for direct)
1. Unzip the models to the folder `tagger/rwtagger/models` 
1. Install virtualenv for Python `pip install virtualenv` 
1. Install pyenv for easy installation and switching between Python versions: [instructions](https://gist.github.com/trongnghia203/9cc8157acb1a9faad2de95c3175aa875)
1. Set up a virtual environment in the folder `tagger` using: `virtualenv rwvenv` 
1. Activate virtual environment: `source rwvenv/local/bin/activate` 
1. Install all required packages in their correct version 
    1. Python 3.7.5 (!!) using pyenv: `pyenv install 3.7.5` 
    1. Switch to Python 3.7.5: `pyenv local 3.7.5` 
    1. pytorch: `pip3.7 install torch==1.10.1` # available for Python 3.7.5
    1. `pip3.7 install torchvision==0.12.0` # Hopefully right version
    1. `pip3.7 install torchaudio==0.11.0` # Hopefully right version
    1. `pip3.7 install flair==0.10`
    1. `pip3.7 install pandas==1.3.5`
    1. `pip3.7 install nltk==3.6.7`
    1. `pip3.7 install pytorch_transformers==1.2.0`
    1. `pip3.7 install openpyxl==3.0.9` # Optional
    1. Go into python3.7 environment with `python3.7`, there do `import nltk` and `nltk.download("punkt")`. Then quit `quit()` 
1. Place a plain text file in the folder `tagger/rwtagger/plain` 
1. Create the folder `tagged-pred` also in `tagger/rwtagger`  
1. From terminal, in folder `tagger/rwtagger`, run: `python3.7 rwtagger.py plain tagged-pred -t direct -conf` 
1. Inspect the resulting TSV file in the folder `tagged-pred` 
1. Correct any mistakes you may find and rename the column `direct_pred` to just `direct`
1. Save the corrected file to a new folder `gold` within `rwtagger` 
1. Create a folder `tagged-test`
1. Run: `python3.7 rwtagger.py -m test gold tagged-test -t direct -conf`  
1. Inspect the results in `tagged-test`, including the scores in `results_stats` 
1. Once all of this works, you are ready to experiment with further models and settings.
